### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by nico-abram** [ecumene-software/rust-slothgl#11]
I tried running with cmd, but it just halted and moved me to the top of the output. Git bash just outputs a bunch of weird characters

**Comment by ecumene** [comment]
Attempt this command: 
`cargo run --release -- models/suzy.obj` 
If this doesn't work, I need a screenshot / copt+past of whatever's happening.
Thanks for the issue report!

**Comment by nico-abram** [comment]
https://i.imgur.com/bl6St2b.png
```
    Finished release [optimized] target(s) in 3.51s
     Running `target\release\sloth.exe models/suzy.obj`
thread '<unnamed>' panicked at 'ste comando." })',  insuficiente para procesar e
```

My system language is currently spanish, apologies.
Note: The process is still running, not doing anything, and if i try ctrl+c it just clears some seemingly random lines of the output text)

Here's the output from git bash: https://i.imgur.com/F6rpiof.png
It just keeps spamming similar messages. Text:
```
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m     ←[38;2;204;42;10m←[48;2;25;25;25mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25mmmm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25mmmm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m   ←[38;2;204;42;10m←[48;2;25;25;25m0mm
←[?25l←[1;1H←[38;2;0;0;0m←[48;2;25;25;25m ←[38;2;204;42;10m←[48;2;25;25;25mm10mm
```

**Comment by ecumene** [comment]
It seems that your teminal doesn't support Ansi escape characters, do you have another terminal you can compile this in and try? For example the windows command prompt?

**Comment by nico-abram** [comment]
The first screenshot and description in the previous post is using the windows command prompt. The second are using git bash.

**Comment by nico-abram** [comment]
Here's a video of what happens when i try to run it using cmder and cmd: https://streamable.com/c9giw

**Comment by nico-abram** [comment]
I tried it again using cmder (And cmd again):
https://i.imgur.com/wv9w0Rx.png
https://i.imgur.com/kGAJ6Ye.png
https://i.imgur.com/LWOwdYB.png
https://i.imgur.com/JJaO5hH.png
https://i.imgur.com/7o8DuYf.png
https://i.imgur.com/FUqNxeM.png

**Comment by ecumene** [comment]
Output of `rustup show`?

**Comment by ecumene** [comment]
It's been a week, and I've got it running fine with 1.36 on powershell and cmd. If your issue persists try updating then come back
